// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXln8IOFaQBBF13NzMzckx19uxLeQdFVw',
    appId: '1:741426971966:web:742ec63b35c90f93da986f',
    messagingSenderId: '741426971966',
    projectId: 'laboratoriomobile-878cc',
    authDomain: 'laboratoriomobile-878cc.firebaseapp.com',
    databaseURL: 'https://laboratoriomobile-878cc-default-rtdb.firebaseio.com',
    storageBucket: 'laboratoriomobile-878cc.appspot.com',
    measurementId: 'G-FT4E8GG144',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkZr96mbVVFzDE5IVrXEUAAFEthaEnG-U',
    appId: '1:741426971966:android:f55d6ed8b87fde54da986f',
    messagingSenderId: '741426971966',
    projectId: 'laboratoriomobile-878cc',
    databaseURL: 'https://laboratoriomobile-878cc-default-rtdb.firebaseio.com',
    storageBucket: 'laboratoriomobile-878cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSc2Y35_VFSwJZoV47Z5uBGSHbXg8R1vE',
    appId: '1:741426971966:ios:36e15a47e80f11b7da986f',
    messagingSenderId: '741426971966',
    projectId: 'laboratoriomobile-878cc',
    databaseURL: 'https://laboratoriomobile-878cc-default-rtdb.firebaseio.com',
    storageBucket: 'laboratoriomobile-878cc.appspot.com',
    iosClientId: '741426971966-5h48crc47878o6ta0numob9hb9picdd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSc2Y35_VFSwJZoV47Z5uBGSHbXg8R1vE',
    appId: '1:741426971966:ios:36e15a47e80f11b7da986f',
    messagingSenderId: '741426971966',
    projectId: 'laboratoriomobile-878cc',
    databaseURL: 'https://laboratoriomobile-878cc-default-rtdb.firebaseio.com',
    storageBucket: 'laboratoriomobile-878cc.appspot.com',
    iosClientId: '741426971966-5h48crc47878o6ta0numob9hb9picdd0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterLoginPage',
  );
}
